### ISSUE TITLE
Text version link

### ISSUE THREAD

**Issue by DessyRascal** [SymfonyCasts/reset-password-bundle#111]
Just installed this bundle for first time - thanks for saving me a job creating this logic btw - but just noticed that the link in the text version of the email is stripped out - not sure if this is an issue with this bundle or Symfony mailer as a text part doesn't seem to be supplied but thought I should highlight it either way

> Hi!
> 
> 
>     To reset your password, please visit
>     here
>     This link will expire in 1 hour(s)..
> 
> 
> 
>     Cheers!

**Comment by jrushlow** [comment]
Good morning @DessyRascal 

The templates are created by `symfony/maker-bundle` `make:reset-password`. Maker generates a pretty basic template that can be edited to suite the user's needs. The email template by default should be located in `templates/reset_password/email.html.twig`. Feel free to modify that for your particular use case.

Having said that, I'm assuming by the "text version" you mean a plain text email without html. If that is the case, this would be the expected behavior. The template uses an [anchor element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) to transform the word "here" into a hyperlink. If your app/users don't support HTML based emails, you would need to change the email template to suite your needs. E.g. use `{{ url('app_reset_password', {token: resetToken.token}) }}` instead of the `<a href...</a>` in the template.

If you are having trouble with the hyperlinks not appearing in HTML based email's, this is most likely not related to the reset password bundle itself. But I'd be happy to point you in the right direction to resolve the issue. 

Thank you for using the bundle
