### ISSUE TITLE
Incorrect typehints?

### ISSUE THREAD

**Issue by BT643** [SymfonyCasts/reset-password-bundle#115]
Is there an issue with the typehints in this?

In the generated ResetPasswordController.php there's this:

```
try {
    $user = $this->resetPasswordHelper->validateTokenAndFetchUser($token);
} catch (ResetPasswordExceptionInterface $e) {
    $this->addFlash('reset_password_error', sprintf(
        'There was a problem validating your reset request - %s',
        $e->getReason()
    ));

    return $this->redirectToRoute('app_forgot_password_request');
}
```
then a little further down:

```
// Encode the plain password, and set it.
$encodedPassword = $passwordEncoder->encodePassword(
    $user,
    $form->get('plainPassword')->getData()
);
```
PHPStorm complains "Expected UserInterface, got object", and something like PHPStan says:

```
 ------ -----------------------------------------------------------------------------------------------------------------------------
  Line   Controller/ResetPasswordController.php
 ------ -----------------------------------------------------------------------------------------------------------------------------
  119    Parameter #1 $user of method Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface::encodePassword() expects
         Symfony\Component\Security\Core\User\UserInterface, object given.
```

Things still work fine but should these be corrected?

**Comment by jrushlow** [comment]
Yes and no. Maker does not type hint user objects (for the ResetPasswordBundle) as a `UserInterface::class` because the reset password bundle itself does not care if the user object is a `UserInterface` or just a plain object. So to be flexible for everyone, we opt'd not to type hint the return value of `$this->resetPasswordHelper->validateTokenAndFetchUser($token);` as `UserInterface` but as `object`. (Same applies to any other method within the Reset Password Bundle that returns a "user" object.)

You can easily add a `/** @var UserInterface */` directly above the  `$user = $this->resetPasswordHelper->validateTokenAndFetchUser($token);` line. That should silence the PHPStan and PHPStorm errors about the wrong object type.

Having said all of that, even if you were to just ignore those "errors", everything should work just fine.
