### ISSUE TITLE
Writing in the db after ensuring mail was sent

### ISSUE THREAD

**Issue by Nayte91** [SymfonyCasts/reset-password-bundle#123]
Hi there,

I played with this bad boy bundle for a while, as I'm doing a project for my studies. I had some troubles to make my smtp work, so I saw some strange behaviors;
First of all, I explain my method:
_I compose with make:reset-password, change nothing about the logic.
_I try to connect to the controller's road, and ensure writing an existing email in the form field.
_I notice that the new reset_password_request's db table is filled with a new line, consequently,
_When I want to redo a test, I just delete the row in this table.

So here's my feedback: If the mail is not sent, (because of smtp blocked, failed authentication, foreign smtp disallowed, ...) That makes a fatal error on my side (big red symfony message, yeah !), and the reset_password_request's row is created. This is a strange behavior for me, because the request is not sent, and the user is still blocked for 1, 2 hours (I didn't notice if the mail can be sent a second time over the "expires_at" time). Because if I retry to submit the email, I trigger the ResetPasswordExceptionInterface catch.

The problem is server side --> the penalty is user side. And that's a problem worth to be told here. At least I guess :)

As I can try something to fix it, I'ld like to bring to you the idea around it:
_I'ld change the reset_password_request by a reset_password_mail table & entity. The other bonus advantage is that you can easily inherit from a "mail" entity, if your app have some sense to do it.
_I'ld say this doesn't need the "expires_at" row/attribute, but this is not the place for that (btw, why did you chose to rely on a db's info rather than a PHP calculus like "created_at" + $duration ? Real question, I'm curious about this choice)
_I'ld display the processSendingPasswordResetEmail() no matter what happens: if the address exist and the mail is sent, if the mail was sent, if the address doesn't exist, ... Because I will not have the info if the email was sent or bloeck by some smtp issue,
_I'ld getback the information from the symfony mailer if OK or not, then write (or not !) the row in reset_password_mail accordingly.

Here's my idea, let me know if you find something that discredits it instantly, what you think about such a change, etc... And thank you for your work !

See you soon,

**Comment by weaverryan** [comment]
Hi @Nayte91!

So, it sounds like the "bad behavior" is that if the email fails to send (bad SMTP connection), that a row IS added to the `reset_password_request` table. That's definitely not what we want :). If you care enough to fix this, you should be able to do it with a database transaction: wrap the delivery of the email in a transaction, and only "commit" the transaction after the email was successfully sent. The reason we don't generate code that does that is just that it's ugly (that's 100% subjective) and if my SMTP connection goes down, that's something we would investigate anyways. And if we cared enough, we would probably have a fallback SMTP server and/or send via Messenger so that the retry functionality can kick in and deliver the email.

So yea, the behavior isn't ideal in this situation. But there are many ways to solve it - we're kinda leaving that to the user :).

Cheers!

**Comment by Nayte91** [comment]
> The reason we don't generate code that does that is just that it's ugly (that's 100% subjective) and if my SMTP connection goes down, that's something we would investigate anyways.

1st statement) I would disagree with as I think there is some simple way to deal with this problem (i.e. catching the TransportExceptionInterface of mailer->send(), and only then processing the block resetPasswordHelper->generateResetToken() ). I don't have perfect solution yet, but,

2nd statement) Well you're right on this one. I'm currently trying some improvement, but in fact:
* If I display the error message from TransportExceptionInterface, then it's a security hole on production, because anyone knows my intimate discussion with my mailer.
* If I don't display it and I stand on a generic 'there was a problem validating your reset request', It's ok on production but I can't debug on dev side. (well with my tools for now. Maybe with tests, xdebug, logs, ...)

As I can't really win against this 2nd argument, I'll let this issue rest in peace. I'll probably open other ones to propose fixes 1 by 1 around the first statement, later.

Thank you for your concern !

**Comment by weaverryan** [comment]
> If I don't display it and I stand on a generic 'there was a problem validating your reset request', It's ok on production but I can't debug on dev side. (well with my tools for now. Maybe with tests, xdebug, logs, ...)

If it helps, what we would do is hide the true error from the user (you're correct that we don't want to expose this!) but log a critical-level log through Monolog. We then have those configured to send to a Slack channel on production so that we're aware of them. In dev, you would still see the generic message - but hopefully it wouldn't be too hard to find :).

Cheers!
