### ISSUE TITLE
Mailer / Mime dependencies

### ISSUE THREAD

**Issue by marchrius** [SymfonyCasts/reset-password-bundle#140]
Is there a reason for this bundle to depend on this libraries?

Is mandatory to send email with mailer or can be sent with any external bundle?

**Comment by bocharsky-bw** [comment]
Because those libraries are awesome :)

In theory, you can use whatever mailer library you want, but MakerBundle only generates code for Symfony Mailer. If you already have a mailer in your system, I'd recommend you to require Symfony Mailer, run that `make:reset-password`, and remove the Symfony Mailer from Composer. Then just replace all mailer calls with your own mailer, it should work. But without Symfony Mailer dependency MakerBundle just won't allow you to generate that code, it's just tight to Symfony's mailer

**Comment by jrushlow** [comment]
Howdy @marchrius, the bundle it self does not require Symfony's Mailer - you are free to send the reset token to the user by any means. But as @bocharsky-bw stated, when using `make:reset-password`, Symfony's MakerBundler creates the `App\Security\EmailVerifier::class` which is responsible for sending out the token's by means of `Mailer`. 

You of course are free to change the logic in the `EmailVerifier:class` to suite your needs if `Mailer` is not an option for your setup. 

Thanks for using the bundle!
