### ISSUE TITLE
Stop using private. Please use protected

### ISSUE THREAD

**Issue by FranzBruckner** [SymfonyCasts/reset-password-bundle#212]
Hey guys,
thanks for this bundle.

To fulfill the story "As Admin i want to send an user a reset-password mail, independently of throttling" i had do tweak the PasswordHelper. Thanks to DI this is not a big deal by just overriding the service-definition for ResetPasswordHelper.

But extending SymfonyCasts\Bundle\ResetPassword\ResetPasswordHelper is a pain, because the use of private members/methods.

**Comment by jrushlow** [comment]
Howdy @FranzBruckner as @bocharsky-bw said, using `protected` instead of `private` for visibility is bad practice unless there is a very specific need to do so. You do have the ability to manipulate `lifetime` and the `throttle_limit` via the bundle [configuration](https://github.com/SymfonyCasts/reset-password-bundle#configuration) to suite the needs of your application. If there is a specific use case, that would benefit everyone, RFC's & PR's are always welcome. 

Thanks for using the bundle!
