### ISSUE TITLE
Some mandatory parameters are missing ("token") to generate a URL for route "app_reset_password".

### ISSUE THREAD

**Issue by StephanotZaf** [SymfonyCasts/reset-password-bundle#254]
If I use php 8.1. I have this error.

**Comment by spetters** [comment]
@StephanotZaf Do you use annotations or attributes? For me with attributes, the following works:

```
<?php
declare(strict_types = 1);

namespace App\Entity;

use App\Repository\ResetPasswordRequestRepository;
use Doctrine\ORM\Mapping as ORM;
use SymfonyCasts\Bundle\ResetPassword\Model\ResetPasswordRequestInterface;
use SymfonyCasts\Bundle\ResetPassword\Model\ResetPasswordRequestTrait;

#[ORM\Entity(repositoryClass: ResetPasswordRequestRepository::class)]
class ResetPasswordRequest implements ResetPasswordRequestInterface {

	use ResetPasswordRequestTrait;

	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column(type: 'integer')]
	private int $id;

	#[ORM\ManyToOne(targetEntity: User::class)]
	#[ORM\JoinColumn(nullable: false)]
	private User $user;

...
```

**Comment by spetters** [comment]
@StephanotZaf How do you generate the link? Do you pass the parameter `token`?

**Comment by mattriecken** [comment]
@StephanotZaf I ran into this issue just now as well on php 8.2. The fix for me was to move the "string $token = null" to the end of the function parameters.

`public function reset(Request $request, UserPasswordHasherInterface $passwordHasher, TranslatorInterface $translator, ManagerRegistry $doctrine, **string $token = null**): Response`

**Comment by weaverryan** [comment]
If anyone hits this, a stacktrace and the code around the error would be awesome :) 

> Not sure why this order mattered, but my IDE was giving me a warning so I moved it around and things started working.

I don't know if changing the order would change how this functioned, but your editor is right that's it's not correct to have an optional argument and then, later, a required one. If MakerBundle generated the optional arg NOT last, definitely let us know - and thanks for sharing your insight :).

**Comment by Merit292005prisy** [comment]
I forgot my learnify.ng password

**Comment by bocharsky-bw** [comment]
I think this issue was fixed already, because as I see the token is the last argument now, and it's also option that makes sense to have it the last after required ones:
`public function reset(Request $request, UserPasswordHasherInterface $passwordHasher, TranslatorInterface $translator, ?string $token = null): Response`

If you experience the same issue on the latest bundle version, feel free to reopen with more details.
