### ISSUE TITLE
New password validaition constraints

### ISSUE THREAD

**Issue by mardon** [SymfonyCasts/reset-password-bundle#314]
May I change configuration for new password parameter eg. passwod length and validation constraints?

**Comment by jrushlow** [comment]
Howdy @mardon - Yes, but, ResetPasswordBundle itself does not really care what the new password will be. This is because  setting the new password is done in, typically, in the `ResetPasswordController::class` which resides in userland code (e.g. your app). 

To have any sort of complexity requirements, I'd recommend looking over https://symfony.com/doc/current/reference/constraints/PasswordStrength.html which you can set on the `User` entity or by creating a validation constraint in the form https://symfony.com/doc/current/forms.html#validating-forms

I'd recommend setting the complexity constraint (or any other "strength" constraints) on the user entity itself as attributes. This way, you'll have the same complexity requirements when the user registers, changes their password (e.g. in their "profile page"), and when they need to use reset-password. 

Let us know if you need any additional help! Thank you!
