### ISSUE TITLE
composer flex requirement

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/reset-password-bundle#50]
Bundle uses flex recipes to initiate it's config.

Either flex ~requirement~, suggestion, or conflict should be added to composer if not covered by the `framework-bundle` conflict

**Comment by jrushlow** [comment]
if in `require` - flex adds `bin`, `config`, `.env`, etc.. in the bundle.. these are not used nor needed...

**Comment by weaverryan** [comment]
If no flex is installed, that's not a problem, It would only affect the README - we would need a small section (maybe) that says "Here's the extra stuff you need to do manually because you don't have Flex installed and so you didn't get the recipe". But there's nothing that we need to do inside the bundle code.

**Comment by jrushlow** [comment]
I think I have that covered in the docs, not 100% I referenced flex. refs PR #51 

closing the issue. between the reference here and a note ill add to the board, think that'll cover it
